import React from 'react';
import { ShieldCheck, Lock, Database, FileCheck, Award } from 'lucide-react';

export const PrivacyTermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div>
        <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">
          Privacy Policy & Terms of Service
        </h2>
        <p className="text-xs text-slate-500 mt-0.5">
          How BillKaro safeguards your business data, customer records, and GST invoicing information
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="p-5 bg-white rounded-2xl border border-slate-200 shadow-xs space-y-2">
          <div className="w-9 h-9 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center">
            <Lock className="w-5 h-5" />
          </div>
          <h4 className="text-sm font-bold text-slate-900">Zero Data Sharing</h4>
          <p className="text-xs text-slate-500 leading-relaxed">
            Your customer phone numbers, GSTINs, and turnover details are never shared, sold, or exposed to third parties.
          </p>
        </div>

        <div className="p-5 bg-white rounded-2xl border border-slate-200 shadow-xs space-y-2">
          <div className="w-9 h-9 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
            <Database className="w-5 h-5" />
          </div>
          <h4 className="text-sm font-bold text-slate-900">Postgres Row Level Security</h4>
          <p className="text-xs text-slate-500 leading-relaxed">
            Every database query is strictly isolated at the database engine level with auth.uid() checks. No user can read another's records.
          </p>
        </div>

        <div className="p-5 bg-white rounded-2xl border border-slate-200 shadow-xs space-y-2">
          <div className="w-9 h-9 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <h4 className="text-sm font-bold text-slate-900">Encrypted Transport</h4>
          <p className="text-xs text-slate-500 leading-relaxed">
            All client-server communications use HTTPS with 256-bit TLS encryption, meeting fintech and GST accounting standards.
          </p>
        </div>
      </div>

      <div className="bg-white rounded-3xl border border-slate-200/80 shadow-xs p-6 sm:p-8 space-y-6 text-xs text-slate-600 leading-relaxed">
        <div className="space-y-2">
          <h3 className="text-sm font-bold text-slate-900">1. Data Storage & Ownership</h3>
          <p>
            You retain 100% ownership of your business data, product catalog, customer directories, and generated tax invoices. BillKaro acts solely as a data processor for your billing operations.
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-sm font-bold text-slate-900">2. Passwordless Authentication & Session Security</h3>
          <p>
            BillKaro utilizes secure email one-time passwords (OTP) and standard cryptographic session tokens. Tokens are managed by Supabase Auth with automatic rotation. No plain-text passwords or financial secrets are logged.
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-sm font-bold text-slate-900">3. GST Compliance & Calculations</h3>
          <p>
            Tax invoices generated by BillKaro include mandatory HSN/SAC codes, CGST/SGST/IGST breakdown, and amount in words formatted in Indian numbering standards. Businesses remain responsible for accurate tax filings with the GST Portal (GSTN).
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-sm font-bold text-slate-900">4. UPI Payments & QR Codes</h3>
          <p>
            UPI QR codes rendered on invoices directly encode standard UPI payment strings (<code className="bg-slate-100 px-1 py-0.5 rounded text-blue-700">upi://pay?pa=...</code>). Payments are settled directly into your linked bank account via UPI without intermediaries.
          </p>
        </div>

        <div className="pt-4 border-t border-slate-100 flex items-center gap-2 text-slate-500 font-medium">
          <Award className="w-4 h-4 text-blue-600" />
          <span>Last Updated: September 2026 � Made with ?? for Indian Small Businesses</span>
        </div>
      </div>
    </div>
  );
};
